version: 0.2
phases:
  pre_build:
    commands:
- echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/b5k3m4u1
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t  nest-test:latest .
      - docker tag nest-test:latest public.ecr.aws/b5k3m4u1/nest:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/b5k3m4u1/nest:latest
      