version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - pip install --upgrade awscli==1.18.17 ### Here is my update - and it works
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t  deepak .
      - docker tag deepak:latest 368772107083.dkr.ecr.ap-south-1.amazonaws.com/test:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 368772107083.dkr.ecr.ap-south-1.amazonaws.com/test:latest
      