version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - pip install --upgrade awscli==2.7.12 ### Here is my update - and it works
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t  nest-test:latest .
      - docker tag nest-test:latest public.ecr.aws/b5k3m4u1/nest:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/b5k3m4u1/nest:latest
      